[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'node workflowy-sql-app/backend/server.js'