[phases.setup]
nixPkgs = ["...", "nodejs-18_x"]

[phases.build]
cmds = [
  "npm install",
  "cd backend && npm install"
]

[phases.start]
cmd = "NODE_ENV=production node server.js"

[variables]
NODE_ENV = "production"
PORT = "3000"