[phases.setup]
nixPkgs = ["...", "nodejs-18_x"]

[phases.build]
cmds = [
  "cd backend",
  "npm install"
]

[phases.start]
cmd = "cd backend && NODE_ENV=production node server-hybrid.js"

[variables]
NODE_ENV = "production"
PORT = "3000"